# -*- coding: utf-8 -*-
"""Enum → CLI map. Keys are 1-based for menu selection."""

DIRECTION_MAP = {1: "BUY", 2: "SELL", 3: "SHORT"}

ORDER_METHOD_MAP = {1: "LIMIT", 2: "MARKET", 3: "MARKET_TO_LIMIT"}

ORDER_DURATION_MAP = {1: "DAILY", 2: "FILL_AND_KILL", 3: "GOOD_TILL_CANCEL"}

ORDER_STATUS_MAP = {1: "NEW", 2: "NOT_SUBMITTED", 3: "SUBMITTED", 4: "PARTIALLY_REALIZED", 5: "REALIZED", 6: "AMENDMENT_REQUESTED", 7: "DIVIDE_WAITING", 8: "CANCEL_REQUESTED", 9: "CANCELLED", 10: "INVALID", 11: "PARTIALLY_SUBMITTED", 12: "DIVIDED", 13: "AMENDMENT_WAITING", 14: "AMENDED", 15: "SENDING", 16: "EXPIRED", 17: "WAITING_FOR_CONDITION", 18: "WAITING"}

EQUITY_TYPE_MAP = {1: "EQUITY", 2: "RIGHTS", 3: "EXCHANGE_TRADED_FUND", 4: "WARRANT", 5: "CERTIFICATE", 6: "REAL_ESTATE_CERTIFICATE", 7: "PROVISIONAL_RECEIPT", 8: "EQUITY_DIVIDEND_MARKET", 9: "EQUITY_PRIMARY_MARKET", 10: "EQUITY_PUBLIC_OFFER_MARKET", 11: "GOLD_CERTIFICATE"}

VIOP_CONTRACT_TYPE_MAP = {1: "FUTURE", 2: "OPTION"}

VIOP_LONG_SHORT_MAP = {1: "LONG", 2: "SHORT"}
